# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5981ebcddf46bae2c79a18726ade951c1988519a0d85f057f4eddb988abd35e1de728058ba54df73a341739625d49d7e1b240bd788fd22646b59f14235d8cc87

test:
  secret_key_base: 0e2ddc03895bd13fbb4381d66d65daa5a47c4edd8862c35c3f85b126aac6062cd9f1ac05c7c6f2d8544d367eaa6524c4e0705a4a30406f239135d605aac01569

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
